### ISSUE TITLE
How to install run?

### ISSUE THREAD

**Issue by cyberfunk** [Roman2K/hist_safari2chrome#1]
I'm not very savvy with ruby commands but I managed to install bundler using "sudo gem install bundler" in Terminal. Now when I run your command, changing the paths to the various db locations, it fails with "Could not locate Gemfile or .bundle/ directory" I see that you have two files called Gemfile in your repository. Where do I put those files?

Here is the code I run. You can see that I have downloaded and placed you import.rb file on my desktop. Is this the correct code to run in Terminal?

bundle exec ruby /Users/Home/Desktop/import.rb /Users/Home/Library/Safari/History.db /Users/Home/Library/Application\ Support/Google/Chrome/Default/History [--verbose --progress]

**Comment by Roman2K** [comment]
Hi @cyberfunk. I'm so sorry for replying this late, I didn't see your issue as I wasn't watching the repo (no idea why)!

I hadn't documented the install/run procedure as I figured someone technical enough to think of running this script would already know how to do it or easily figure it out.

Do you still need assistance?

**Comment by cyberfunk** [comment]
Hi thanks for the follow-up. I no longer require assistance. It's been so long that I made it successfully over to Firefox and I'm back on Safari now that Apple has introduced dark mode with Mojave. I don't think I ever got this to work but did find another solution so everything worked out in the end.😀

**Comment by Roman2K** [comment]
Okay perfect then! I'm glad you sorted this out 😉

**Comment by sinepgnol** [comment]
@Roman2K Could you please help me with your script? 
I run `bundle exec ruby import.rb safari.db chrome.db [--verbose --progress] `in terminal and I get this error: `import.rb:224:in `<main>': unhandled options: --progress] (ArgumentError)`

I also tried running it without the parameters: `bundle exec ruby import.rb safari.db chrome.db` and I got this error: ```
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:91:in `initialize': no such table: history_visits (SQLite3::SQLException)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:91:in `new'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:91:in `prepare'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:134:in `execute'
	from import.rb:161:in `urls'
	from import.rb:76:in `copy'
	from import.rb:28:in `import'
	from import.rb:233:in `<main>'
```

Could you help me please? Thank you very much in advance

**Comment by sinepgnol** [comment]
Thank you for your help but after running as you suggested I get the following error, do you have any idea on what that could be caused by?
<img width="1416" alt="screenshot 2018-11-27 at 17 36 30" src="https://user-images.githubusercontent.com/45313882/49096689-5f5aaa80-f26b-11e8-99b0-cd7504999bd7.png">
Thanks

**Comment by Roman2K** [comment]
@sinepgnol The final `s` of the last argument `--progress` got lost in your copy/paste, haha!

**Comment by sinepgnol** [comment]
Including the final "s", I got a different error, therefore I move both my Safari history file and the Chrome history file to Desktop and got a completely different error again, please see the attached image:
<img width="1646" alt="screenshot 2018-11-27 at 21 32 45" src="https://user-images.githubusercontent.com/45313882/49109865-27b02a80-f28c-11e8-8334-ad56858a8ff0.png">

**Comment by Roman2K** [comment]
@sinepgnol Sorry you're having to go through all that. You're facing what I thought might happen:
> To be noted though: I haven't tested the script in a long time. Should either Safari or Chrome have updated their database schemas, you will get errors. I don't have any Mac to test on anymore, sorry.

Hehe... But luckily, @opais solved it in https://github.com/Roman2K/hist_safari2chrome/pull/2 (I didn't personally test it but the changes look OK). You'll have to switch to his fork first. To do so, within your existing hist_safari2chrome/ directory, run:

```
$ git remote add opais https://github.com/opais/hist_safari2chrome
$ git fetch opais
$ git checkout -b opais opais/master
```
And try again.

**Comment by sinepgnol** [comment]
Thank you very much for your assistance, I already accomplished that using this guide: [](https://gist.github.com/dropmeaword/9372cbeb29e8390521c2)

**Comment by Roman2K** [comment]
Oh OK! That gist is very good. [It's acually the basis](https://gist.github.com/dropmeaword/9372cbeb29e8390521c2#gistcomment-1887474) for hist_safari2chrome.

Glad you worked it out!
