### ISSUE TITLE
no such table: history_visits (SQLite3::SQLException)

### ISSUE THREAD

**Issue by duplex143** [Roman2K/hist_safari2chrome#3]
After executing, `bundle exec ruby import.rb safari.db chrome.db`
Getting this error:
```
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:91:in `initialize': no such table: history_visits (SQLite3::SQLException)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:91:in `new'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:91:in `prepare'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:134:in `execute'
	from import.rb:160:in `urls'
	from import.rb:76:in `copy'
	from import.rb:28:in `import'
	from import.rb:232:in `<main>'
```

**Comment by targetbyte** [comment]
The Command "bundle exec ruby import.rb safari.db chrome.db" is a Placeholder Command

1. first quit chrome to be sure there is no damaging
2. go to the project folder of this project
3. follow these instructions
```
# make a backup of original files
cp -p ~/Library/Safari/History.db ~/Library/Safari/History.backup.db 
# Copy History of Safari to local project folder
cp -p ~/Library/Safari/History.db ./safari.db

# make a backup of original files
cp -p ~/Library/Application\ Support/Google/Chrome/Default/History cp -p ~/Library/Application\ Support/Google/Chrome/Default/History.backup
# Copy History of Safari to local project folder
cp -p ~/Library/Application\ Support/Google/Chrome/Default/History ./chrome.db

bundle exec ruby import.rb safari.db chrome.db  --verbose --progress
```
4. after all you should see something like:

100.00% ███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ 327414 of 327414 @ 1102/s
Removed 5208 duplicates

5. now copy back the new crome.db to History-Path where Chrome is looking
```
cp -p  ./chrome.db ~/Library/Application\ Support/Google/Chrome/Default/History
```
happy switching :-)
cheers

**Comment by Roman2K** [comment]
@duplex143 Sorry for the extremely late response. This script is intended for users who did a bit of research about each browser's SQLite database file path and would then understand reading this project's README that `safari.db` and `chrome.db` are sample paths to replace with real ones, or actual relative paths to copies of them. @targetbyte's instructions are spot on 😉

**Comment by sumanth-98-dev** [comment]
If anyone is facing `Operation not permitted` for `cp` commands, follow the instructions in https://osxdaily.com/2018/10/09/fix-operation-not-permitted-terminal-error-macos/
